# ManusUse Configuration for AWS Bedrock

[llm]
# Use AWS Bedrock
provider = "bedrock"

# Model options for Bedrock:
# - "us.anthropic.claude-opus-4-20250514-v1:0"
# - "us.anthropic.claude-3-5-sonnet-20241022-v2:0"
# - "us.anthropic.claude-3-5-haiku-20241022-v1:0"
# - "us.amazon.nova-pro-v1:0"
# - "us.amazon.nova-lite-v1:0"
# - us.anthropic.claude-sonnet-4-20250514-v1:0
model = "us.anthropic.claude-3-7-sonnet-20250219-v1:0"

# Model parameters
temperature = 0.0
max_tokens = 4096

[sandbox]
# Disable Docker sandbox for initial testing
enabled = false

[tools]
# Enable basic tools for testing
enabled = ["file_operations", "code_execute", "web_search"]

# Browser settings
browser_headless = false

# Search engine
search_engine = "duckduckgo"
max_search_results = 3